### ISSUE TITLE
Free Pascal compatible

### ISSUE THREAD

**Issue by mdbs99** [EtheaDev/kitto2#2]
Is this project compatible with Free Pascal?
If not, would you say is it a possibility in a near future?

**Comment by nandod** [comment]
Hi; I don't know much of FreePascal so I couldn't say. The Kitto engine could probably be ported much more easily than KIDE. The project doesn't currently have any plans to do so, though.

**Comment by mdbs99** [comment]
ExtPascal was written in Free Pascal as primary compiler.
Kitto could get many other users from Free Pascal | Lazarus if the code is compatible.
OK, currently you do not have any plans to do so. But if you had colaborators for these, it would be appreciated?

**Comment by nandod** [comment]
Kitto doesn't use ExtPascal since quite a long time, although it retains some of the concepts and possibly some of the code. I personally have no objections if you want to clone the repo and give a try to porting the code to FPC.

**Comment by mdbs99** [comment]
> Kitto doesn't use ExtPascal since quite a long time

I know. It was just for you know that is quite possible to do this work.
First, I asked in FPC|Lazarus list if someone is already working on this...

I'll keep in touch. Thanks.
(please keep this issue open for a while)

**Comment by mdbs99** [comment]
OK, I will take a look more closer. If I have news, I will open a new issue for it. Thanks.
