### ISSUE TITLE
Errori in compilazione 

### ISSUE THREAD

**Issue by blade1959** [EtheaDev/kitto2#5]
Volendolo provare compilando riscontro:
1) Kitto.Ext.ResetPassword.pas mancante in kittocore250
2) In KIDE.IOTA.ProjectCreator.pas GetProjectName undeclared
3) In Kide.Project FServer.AddRoute undeclared identifier (forse FServer.Engine.AddRoute?)
4) In Kide.Utils TProject.CurrentProject.Config.FindImagePathName undeclared
5) In Kide.MainformUnit Kitto.Ext.MainFormUnit unit not found

Thank

**Comment by carloBarazzetta** [comment]
Thanks for the report, the compilation errors have been solved.
